version: "3"
services:
  discord-bot:
    container_name: Discord-Hr-Music-bot
    restart: unless-stopped
    image: harshraj9812/hr-bot-jmusicbot:0.3.9
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      # Add your Bot TOken below
      - TOKEN=[BOT TOKEN]