apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discord-bot-statefulset
spec:
  serviceName: "discord-bot"
  replicas: 3
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: harshraj9812/hr-bot-jmusicbot:0.3.9
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secret
              key: TOKEN
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
