name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Fetch latest JMusicBot release
        run: |
          latest_release=$(curl --silent "https://api.github.com/repos/jagrosh/MusicBot/releases/latest" | jq -r '.tag_name')
          echo "Latest release version: $latest_release"
          curl -LJO "https://github.com/jagrosh/MusicBot/releases/download/$latest_release/JMusicBot-$latest_release.jar"
          mv JMusicBot-$latest_release.jar JMusicBot.jar

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --tag your-docker-hub-username/jmusicbot-image:latest --platform linux/amd64,linux/arm64 .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push your-docker-hub-username/jmusicbot-image:latest
