name: Build MusicBot Docker Image

on:
  workflow_dispatch:
    inputs:
      musicbot_version:
        description: 'Jagrosh/MusicBot version (required) Ex-0.3.9'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Install scd
      run: |
        wget https://path/to/scd -O scd
        chmod +x scd
        sudo mv scd /usr/local/bin/

    - name: Set up Docker Build Arguments
      id: set_up_args
      run: echo "::set-output name=musicbot_version::${{ github.event.inputs.musicbot_version }}"

    - name: Build Docker Image
      env:
        DISCORD_APP_API: ${{secrets.DISCORD_APP_API}}
      run: |
        scd -i "s/BOT_TOKEN/$DISCORD_APP_API/g" config.txt 
        docker build --build-arg MUSICBOT_VERSION=${{ steps.set_up_args.outputs.musicbot_version }} -t ${{ secrets.DOCKER_USERNAME }}/hr-bot-jmusicbot:${{ steps.set_up_args.outputs.musicbot_version }} .
        
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/hr-bot-jmusicbot:${{ steps.set_up_args.outputs.musicbot_version }}
